#!/usr/bin/env python3
"""Copy mods/shared/*.ts into each mod plugin's hooks/lib/ (one source, named holders).

A mod may import only its own files, so each plugin carries a copy of the shared files it
uses. HOLDERS names them: dash holds the whole library; privacy holds only the switch file
reader, the catalog and the small helpers, so its safety code never waits on dashboard code.
Edit mods/shared/, never a copy. `--check` exits 1 on any drift, for CI.

Usage:
  python mods/sync_shared.py          # write the copies
  python mods/sync_shared.py --check  # report drift only
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SHARED = ROOT / "shared"
HEADER = "// GENERATED by mods/sync_shared.py from mods/shared/{name}. Edit the source, not this copy.\n"

# plugin -> shared files it holds; "*" is every file in mods/shared.
HOLDERS = {
    "dash": "*",
    "privacy": ["catalog.ts", "switches.ts", "util.ts"],
}


def plugins():
    """Every folder under mods/ with a plugin manifest and a hooks module."""
    return sorted(p for p in ROOT.iterdir() if (p / ".claude-plugin" / "plugin.json").is_file() and (p / "hooks" / "hooks.json").is_file())


def held(name: str) -> list[Path]:
    want = HOLDERS.get(name)
    every = sorted(SHARED.glob("*.ts"))
    if want == "*":
        return every
    return [SHARED / n for n in (want or [])]


def main() -> int:
    check = "--check" in sys.argv[1:]
    drift = []
    found = plugins()
    names = {p.name for p in found}
    for name in sorted(set(HOLDERS) - names):
        drift.append(f"{name} (named in HOLDERS, no plugin folder)")
    for name in sorted(names - set(HOLDERS)):
        drift.append(f"{name} (a plugin with no HOLDERS row)")
    for src in [s for n in HOLDERS for s in held(n)]:
        if not src.is_file():
            drift.append(f"shared/{src.name} (named in HOLDERS, missing)")
    for plugin in found:
        lib = plugin / "hooks" / "lib"
        sources = [s for s in held(plugin.name) if s.is_file()]
        for src in sources:
            want = HEADER.format(name=src.name) + src.read_text(encoding="utf-8")
            dest = lib / src.name
            have = dest.read_text(encoding="utf-8") if dest.is_file() else None
            if have != want:
                drift.append(str(dest.relative_to(ROOT)))
                if not check:
                    lib.mkdir(parents=True, exist_ok=True)
                    dest.write_text(want, encoding="utf-8", newline="\n")
        # A file left in hooks/lib/ that this plugin does not hold is stale and would ship.
        if lib.is_dir():
            keep = {s.name for s in sources}
            for extra in sorted(lib.glob("*.ts")):
                if extra.name not in keep:
                    drift.append(str(extra.relative_to(ROOT)) + " (not held by this plugin)")
                    if not check:
                        extra.unlink()
    if check and drift:
        print("sync_shared: drift in " + ", ".join(drift))
        return 1
    print(f"sync_shared: {'checked' if check else 'wrote'} {len(found)} plugin(s); {len(drift)} file(s) {'drifted' if check else 'updated'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
