"""Tests for gatewarden's reach scripts (map, footprint, drive rules, treemap, drift, loads).
Stdlib unittest; every fixture lives in a temp folder.

    python -m unittest discover -s scripts -p "test_*.py"
"""
from __future__ import annotations

import io
import json
import os
import shutil
import sys
import tempfile
import unittest
from contextlib import redirect_stdout, redirect_stderr
from pathlib import Path
from unittest import mock

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import drift  # noqa: E402
import footprint  # noqa: E402
import drive_rules  # noqa: E402
import loads  # noqa: E402
import scan_tree  # noqa: E402
import treemap_page  # noqa: E402

FAKE_KEY = "sk-" + "live" + "A1b2C3d4E5f6G7h8I9j0K1l2"  # built at runtime: a secret shape, not a secret


def make_link(target: Path, link: Path) -> str:
    """A junction on Windows (no admin needed), a symlink elsewhere. Returns the kind made."""
    if os.name == "nt":
        import _winapi
        _winapi.CreateJunction(str(target), str(link))
        return "junction"
    os.symlink(target, link, target_is_directory=True)
    return "symlink"


def run(fn, argv):
    out, err = io.StringIO(), io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        code = fn(argv)
    return code, out.getvalue(), err.getvalue()


class Base(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="gw-reach-"))

    def tearDown(self):
        # remove links first so rmtree never walks through one
        for dp, dns, fns in os.walk(self.tmp, topdown=True):
            for d in list(dns):
                p = Path(dp) / d
                if p.is_symlink() or (hasattr(p, "is_junction") and p.is_junction()):
                    os.rmdir(p) if os.name == "nt" else p.unlink()
                    dns.remove(d)
        shutil.rmtree(self.tmp, ignore_errors=True)


class ScanTreeTests(Base):
    def test_junction_loop_is_listed_once_and_not_followed(self):
        root = self.tmp / "tree"
        (root / "a" / "b").mkdir(parents=True)
        (root / "a" / "b" / "f.bin").write_bytes(b"x" * 1000)
        kind = make_link(root, root / "a" / "loop")   # points back at its own ancestor
        code, _, _ = run(scan_tree.main, [str(root), "--json", str(self.tmp / "s.json"), "--depth", "5"])
        scan = json.loads((self.tmp / "s.json").read_text(encoding="utf-8"))
        self.assertEqual(code, 0)
        self.assertEqual(scan["totals"]["bytes"], 1000)          # counted once, loop not followed
        self.assertEqual(len(scan["links"]), 1)
        self.assertEqual(scan["links"][0]["kind"], kind)
        self.assertTrue(scan["links"][0]["path"].endswith("a/loop"))

    def test_repo_detection_and_top_files(self):
        root = self.tmp / "tree"
        (root / "proj" / ".git").mkdir(parents=True)
        (root / "proj" / "big.dat").write_bytes(b"y" * 5000)
        (root / "small.txt").write_bytes(b"z")
        run(scan_tree.main, [str(root), "--json", str(self.tmp / "s.json")])
        scan = json.loads((self.tmp / "s.json").read_text(encoding="utf-8"))
        self.assertEqual(len(scan["repos"]), 1)
        self.assertTrue(scan["top_files"][0]["path"].endswith("proj/big.dat"))

    def test_wiztree_import(self):
        root = self.tmp / "drive"
        root.mkdir()
        base = str(root).replace("/", "\\")
        csv_text = ("Generated by WizTree\n"
                    "File Name,Size,Allocated,Modified,Attributes,Files,Folders\n"
                    f'"{base}\\",3000,4096,,,2,1\n'
                    f'"{base}\\games\\",2500,4096,,,1,0\n'
                    f'"{base}\\games\\big.pak",2500,4096,,,0,0\n'
                    f'"{base}\\note.txt",500,4096,,,0,0\n')
        (self.tmp / "w.csv").write_text(csv_text, encoding="utf-8")
        code, _, err = run(scan_tree.main, [str(root), "--from-wiztree", str(self.tmp / "w.csv"),
                                            "--json", str(self.tmp / "s.json")])
        self.assertEqual(code, 0, err)
        scan = json.loads((self.tmp / "s.json").read_text(encoding="utf-8"))
        self.assertEqual(scan["source"], "wiztree")
        self.assertEqual(scan["totals"]["bytes"], 3000)
        self.assertEqual(scan["tree"]["children"][0]["name"], "games")


class FootprintTests(Base):
    def build_home(self):
        home = self.tmp / "claude-home"
        work = self.tmp / "work"
        extra = self.tmp / "granted-unused"
        elsewhere = self.tmp / "elsewhere"
        for d in (work, extra, elsewhere, home / "projects" / "p1"):
            d.mkdir(parents=True)
        (home / "settings.json").write_text(json.dumps(
            {"permissions": {"additionalDirectories": [str(extra)]}}), encoding="utf-8")
        cwd = str(work)
        recs = [
            {"type": "assistant", "cwd": cwd, "timestamp": "2999-01-01T00:00:00Z",
             "message": {"content": [{"type": "tool_use", "name": "Read",
                                      "input": {"file_path": str(work / "a.txt")}}]}},
            {"type": "assistant", "cwd": cwd, "timestamp": "2999-01-01T00:00:01Z",
             "message": {"content": [{"type": "tool_use", "name": "Write",
                                      "input": {"file_path": str(elsewhere / "out.txt"),
                                                "content": "BODY-TEXT-NEVER-PRINTED"}}]}},
            {"type": "assistant", "cwd": cwd, "timestamp": "2999-01-01T00:00:02Z",
             "message": {"content": [{"type": "tool_use", "name": "Bash",
                                      "input": {"command": f"curl -H 'Authorization: Bearer {FAKE_KEY}' "
                                                           f"--token={FAKE_KEY} -o {elsewhere / 'dl.bin'}"}}]}},
            "not json at all",
        ]
        lines = [r if isinstance(r, str) else json.dumps(r) for r in recs]
        (home / "projects" / "p1" / "s1.jsonl").write_text("\n".join(lines) + "\n", encoding="utf-8")
        return home

    def run_fp(self, home, *extra):
        out = self.tmp / "fp.json"
        code, _, err = run(footprint.main, ["--claude-home", str(home), "--temp", str(self.tmp / "no-temp"),
                                            "--claude-json", str(self.tmp / "none.json"),
                                            "--depth", "99", "--json", str(out), *extra])
        self.assertEqual(code, 0, err)
        return json.loads(out.read_text(encoding="utf-8")), out.read_text(encoding="utf-8")

    def test_fields_only_reports_field_names_and_no_paths_or_values(self):
        """Owner Q37: the first live footprint reports field names only."""
        home = self.build_home()
        fp, raw = self.run_fp(home, "--fields-only")
        self.assertEqual(fp["mode"], "fields")
        self.assertIn("cwd", fp["record_fields"])
        self.assertEqual(fp["record_fields"]["timestamp"], 3)
        self.assertEqual(sorted(fp["tool_input_fields"]["Write"]), ["content", "file_path"])
        self.assertEqual(fp["tool_input_fields"]["Bash"], ["command"])
        self.assertEqual(fp["skipped_lines"], 1)
        for leak in ("BODY-TEXT-NEVER-PRINTED", FAKE_KEY, "elsewhere", "work", "a.txt", str(self.tmp), "p1"):
            self.assertNotIn(leak, raw)

    def test_unreadable_transcript_is_counted_not_fatal(self):
        """First live run (2026-10-02): a transcript past the Windows path limit raised on stat()
        and crashed the run. It must be counted and skipped in both modes."""
        home = self.build_home()
        bad = home / "projects" / "p1" / "UNREADABLE-session.jsonl"
        bad.write_text('{"type":"user"}\n', encoding="utf-8")
        real_stat = Path.stat

        def flaky_stat(p, *a, **k):
            if "UNREADABLE" in str(p):
                raise FileNotFoundError(3, "The system cannot find the path specified", str(p))
            return real_stat(p, *a, **k)

        with mock.patch.object(Path, "stat", flaky_stat):
            fp, raw = self.run_fp(home, "--fields-only")
            self.assertEqual(fp["unreadable_files"], 1)
            fp2, _ = self.run_fp(home)
            self.assertEqual(fp2["unreadable_files"], 1)
        self.assertNotIn("UNREADABLE", raw)

    def test_reached_not_granted_and_granted_never_reached(self):
        fp, _ = self.run_fp(self.build_home())
        rng = [r["root"] for r in fp["reached_not_granted"]]
        self.assertTrue(any("elsewhere" in r for r in rng), rng)
        self.assertFalse(any(r.endswith("work/a.txt") for r in rng))       # inside the session cwd
        self.assertTrue(any(g["root"].endswith("granted-unused") for g in fp["granted_never_reached"]))
        self.assertEqual(fp["skipped_lines"], 1)
        write_row = next(r for r in fp["reach"] if r["root"].endswith("elsewhere/out.txt"))
        self.assertEqual(write_row["write"], 1)

    def test_no_secret_command_text_or_content_in_output(self):
        _, raw = self.run_fp(self.build_home())
        self.assertNotIn(FAKE_KEY, raw)
        self.assertNotIn("Bearer", raw)
        self.assertNotIn("curl", raw)
        self.assertNotIn("BODY-TEXT-NEVER-PRINTED", raw)
        self.assertIn("dl.bin", raw)                                       # the path itself survives

    def test_orphaned_project_and_worktree(self):
        home = self.build_home()
        gone = self.tmp / "deleted-project"
        (home / "projects" / "p2").mkdir()
        (home / "projects" / "p2" / "s2.jsonl").write_text(
            json.dumps({"type": "user", "cwd": str(gone)}) + "\n", encoding="utf-8")
        wt = self.tmp / "work" / ".claude" / "worktrees" / "agent-x"
        wt.mkdir(parents=True)
        (wt / ".git").write_text("gitdir: " + str(self.tmp / "missing-gitdir") + "\n", encoding="utf-8")
        fp, _ = self.run_fp(home)
        kinds = {o["kind"] for o in fp["orphans"]}
        self.assertIn("project-transcripts", kinds)
        self.assertIn("worktree", kinds)

    def test_shell_paths_drop_secrets_and_urls(self):
        drive = "q" + ":/"   # built at runtime
        toks = footprint.shell_paths(f"x --key={FAKE_KEY} https://example.org/a {drive}data/file.txt ~/notes")
        self.assertEqual(toks, [drive + "data/file.txt", "~/notes"])

    def test_old_transcripts_outside_window_are_ignored(self):
        home = self.build_home()
        f = home / "projects" / "p1" / "s1.jsonl"
        os.utime(f, (1, 1))
        fp, _ = self.run_fp(home)
        self.assertEqual(fp["events"], 0)


class LayoutTests(Base):
    def test_repo_outside_roots_and_forbidden_folder(self):
        root = self.tmp / "estate"
        (root / "github" / "acct" / "good" / ".git").mkdir(parents=True)
        (root / "loose" / ".git").mkdir(parents=True)
        (root / "github" / "acct" / "good" / "node_modules").mkdir()
        run(scan_tree.main, [str(root), "--json", str(self.tmp / "s.json"), "--depth", "6"])
        rules = {"rules": [{"name": "repos-only-under-github", "kind": "repo_roots", "allow": ["github/*/*"]},
                           {"name": "no-node-modules", "kind": "forbidden", "pattern": "**/node_modules"}]}
        (self.tmp / "r.json").write_text(json.dumps(rules), encoding="utf-8")
        code, _, _ = run(drive_rules.main, [str(self.tmp / "s.json"), "--rules", str(self.tmp / "r.json"),
                                             "--json", str(self.tmp / "f.json")])
        found = json.loads((self.tmp / "f.json").read_text(encoding="utf-8"))["findings"]
        self.assertEqual(code, 1)
        self.assertEqual({f["rule"] for f in found}, {"repos-only-under-github", "no-node-modules"})
        self.assertTrue(any(f["path"].endswith("loose") for f in found))

    def test_builtin_nested_repo_and_dead_link_without_rules(self):
        root = self.tmp / "estate"
        (root / "outer" / ".git").mkdir(parents=True)
        (root / "outer" / "vendor" / "inner" / ".git").mkdir(parents=True)
        gone = self.tmp / "gone-target"
        gone.mkdir()
        make_link(gone, root / "dead")
        gone.rmdir()
        run(scan_tree.main, [str(root), "--json", str(self.tmp / "s.json"), "--depth", "6"])
        code, _, _ = run(drive_rules.main, [str(self.tmp / "s.json"), "--json", str(self.tmp / "f.json")])
        found = json.loads((self.tmp / "f.json").read_text(encoding="utf-8"))["findings"]
        self.assertEqual(code, 1)
        self.assertEqual({f["rule"] for f in found}, {"builtin:nested-repo", "builtin:dead-link"})

    def test_bad_rules_file_is_input_error(self):
        (self.tmp / "s.json").write_text("{}", encoding="utf-8")
        (self.tmp / "r.json").write_text(json.dumps({"rules": [{"kind": "delete_everything"}]}), encoding="utf-8")
        code, _, _ = run(drive_rules.main, [str(self.tmp / "s.json"), "--rules", str(self.tmp / "r.json")])
        self.assertEqual(code, 2)


class TreemapTests(Base):
    def test_page_is_self_contained(self):
        root = self.tmp / "t"
        (root / "x").mkdir(parents=True)
        (root / "x" / "f").write_bytes(b"1" * 10)
        (root / "x" / "evil<!--<script>alert(1)").mkdir() if os.name != "nt" else None
        run(scan_tree.main, [str(root), "--json", str(self.tmp / "s.json")])
        code, _, _ = run(treemap_page.main, [str(self.tmp / "s.json"), "--out", str(self.tmp / "m.html")])
        page = (self.tmp / "m.html").read_text(encoding="utf-8")
        self.assertEqual(code, 0)
        self.assertNotIn("http://", page)
        self.assertNotIn("https://", page)
        self.assertNotIn("<script src", page)
        self.assertEqual(page.count("</script>"), 1)                     # embedded data cannot close the tag
        self.assertIn("Publish only on the owner's word", page)


class DriftTests(Base):
    def test_drift_and_linked_pairs(self):
        live, tracked = self.tmp / "live", self.tmp / "tracked"
        live.mkdir(); tracked.mkdir()
        (live / "hook.py").write_text("a = 1\n", encoding="utf-8")
        (tracked / "hook.py").write_text("a = 2\n", encoding="utf-8")
        (tracked / "extra.py").write_text("b\n", encoding="utf-8")
        (live / "same.txt").write_bytes(b"line\r\n")
        (tracked / "same.txt").write_bytes(b"line\n")                  # line endings are not drift
        linked = self.tmp / "linked"
        make_link(tracked, linked)
        code, _, _ = run(drift.main, ["--pair", str(live), str(tracked), "--pair", str(linked), str(tracked),
                                      "--json", str(self.tmp / "d.json")])
        d = json.loads((self.tmp / "d.json").read_text(encoding="utf-8"))
        self.assertEqual(code, 1)
        self.assertEqual(d["pairs"][0]["state"], "drift")
        self.assertEqual({x["file"]: x["state"] for x in d["pairs"][0]["diffs"]},
                         {"hook.py": "differs", "extra.py": "only-tracked"})
        self.assertEqual(d["pairs"][1]["state"], "linked")

    def test_inventory_owner(self):
        repo = self.tmp / "repo"
        (repo / ".git").mkdir(parents=True)
        (repo / "skills" / "one").mkdir(parents=True)
        inst = self.tmp / "installed"
        inst.mkdir()
        make_link(repo / "skills" / "one", inst / "one")
        (inst / "loose").mkdir()
        run(drift.main, ["--inventory", str(inst), "--json", str(self.tmp / "i.json")])
        inv = {Path(i["entry"]).name: i for i in json.loads((self.tmp / "i.json").read_text(encoding="utf-8"))["inventory"]}
        self.assertTrue(inv["one"]["owner"].endswith("repo"))
        self.assertEqual(inv["loose"]["owner"], "none")


class LoadsTests(Base):
    MARK = "BODY-MARKER-NEVER-PRINTED"

    def skill(self, folder: Path, name: str, body: str = "same", fm: str | None = None):
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "SKILL.md").write_text(f"---\nname: {fm or name}\ndescription: d\n---\n{self.MARK} {body}\n",
                                         encoding="utf-8")

    def fixture(self):
        home, proj = self.tmp / "home", self.tmp / "proj"
        us = home / "skills"
        self.skill(us / "twin-stale", "twin-stale", "new")
        self.skill(us / "twin-off", "twin-off")
        self.skill(us / "twin-open", "twin-open")
        self.skill(us / "dual", "dual")
        self.skill(us / "scoped", "scoped", "user")
        self.skill(us / "plugged", "plugged")
        self.skill(us / "quiet", "quiet")
        self.skill(self.tmp / "repo" / "linked", "linked")
        make_link(self.tmp / "repo" / "linked", us / "linked")
        self.skill(us / "other-folder", "x", fm="dual")                  # two folders, one SKILL.md name
        self.skill(proj / ".claude" / "skills" / "scoped", "scoped", "project")
        acct = us / "synced" / "acct"
        for n, body in [("twin-stale", "old"), ("twin-off", "same"), ("twin-open", "same"),
                        ("retired-one", "r"), ("companion", "c"), ("pdf", "p")]:
            self.skill(acct / n, n, body)
        man = [{"name": n, "source": "plugin", "creatorType": "user"}
               for n in ("twin-stale", "twin-off", "twin-open", "retired-one", "companion")]
        man.append({"name": "pdf", "source": "anthropic", "creatorType": "anthropic"})
        (acct / "manifest.json").write_text(json.dumps({"skills": man}), encoding="utf-8")
        inst = home / "plugins" / "cache" / "mk" / "plug" / "1.0.0"
        self.skill(inst / "skills" / "plugged", "plugged")
        (inst / ".claude-plugin").mkdir(parents=True)
        (inst / ".claude-plugin" / "plugin.json").write_text('{"name": "plug"}', encoding="utf-8")
        off_inst = home / "plugins" / "cache" / "mk" / "offplug" / "1.0.0"
        self.skill(off_inst / "skills" / "quiet", "quiet")
        (home / "plugins" / "installed_plugins.json").write_text(json.dumps({"version": 2, "plugins": {
            "plug@mk": [{"scope": "user", "installPath": str(inst), "version": "1.0.0"}],
            "offplug@mk": [{"scope": "user", "installPath": str(off_inst), "version": "1.0.0"}]}}),
            encoding="utf-8")
        (home / "settings.json").write_text(json.dumps({
            "skillOverrides": {"anthropic-skills:twin-off": "off", "keep-me": "name-only"},
            "enabledPlugins": {"plug@mk": True, "offplug@mk": False}}), encoding="utf-8")
        return home, proj

    def test_kinds_handled_and_settings_block(self):
        home, proj = self.fixture()
        code, out, _ = run(loads.main, ["--home", str(home), "--project", str(proj),
                                        "--retired", "retired-one", "--json", "-"])
        d = json.loads(out)
        rows = {r["skill"]: r for r in d["rows"]}
        self.assertEqual(code, 1)
        self.assertEqual(rows["twin-stale"]["kinds"], [1, 5])
        self.assertEqual(rows["twin-stale"]["bodies"], "differ")
        self.assertEqual(rows["twin-off"]["status"], "handled")
        self.assertTrue(rows["twin-off"]["handled"])
        self.assertEqual(rows["twin-open"]["status"], "finding")
        self.assertEqual(rows["retired-one"]["status"], "finding")
        self.assertEqual(rows["companion"]["status"], "review")
        self.assertEqual(rows["plugged"]["kinds"], [3])
        self.assertIn("claude plugin uninstall plug@mk", rows["plugged"]["fix"][0])
        self.assertIn(4, rows["scoped"]["kinds"])
        self.assertIn(4, rows["dual"]["kinds"])
        for absent in ("pdf", "quiet", "linked"):                     # built-in, disabled plugin, junction
            self.assertNotIn(absent, rows)
        block = d["settings_block"]["skillOverrides"]
        self.assertEqual(block["keep-me"], "name-only")                  # existing entries kept
        for k in ("twin-off", "twin-stale", "twin-open", "retired-one"):
            self.assertEqual(block[f"anthropic-skills:{k}"], "off")
        self.assertNotIn("anthropic-skills:companion", block)
        self.assertNotIn(self.MARK, out)
        settings = json.loads((home / "settings.json").read_text(encoding="utf-8"))
        self.assertNotIn("anthropic-skills:twin-open", settings["skillOverrides"])   # never writes

    def test_table_and_missing_sources(self):
        home = self.tmp / "bare"
        home.mkdir()
        code, out, _ = run(loads.main, ["--home", str(home), "--project", str(self.tmp)])
        self.assertEqual(code, 0)
        self.assertIn("not checked:", out)
        self.assertIn("synced skills manifest", out)
        code, _, err = run(loads.main, ["--home", str(self.tmp / "nope")])
        self.assertEqual(code, 2)


if __name__ == "__main__":
    unittest.main()
