// GENERATED by mods/sync_shared.py from mods/shared/shell.ts. Edit the source, not this copy.
// One shell reader. It turns a command line into the simple commands that would really run,
// after unwrapping the shapes that hide a command from a plain reading. Heredoc bodies, comments
// and quoted text stay data; anything it cannot read for sure sets `indeterminate`. dash uses it
// for command shapes (never the text), the switch-file check and the Godot panel.

export type Redirect = { op: string; target: string }

export type SimpleCommand = {
  /** The words as the shell would pass them, quotes and splices removed. */
  argv: string[]
  /** Lower-cased program name without folder or .exe. */
  prog: string
  /** Variable assignments in front of the command (`X=1 cmd`, `$env:X = 1` is its own command). */
  env: Record<string, string>
  redirects: Redirect[]
  /** The folder a `cd` earlier on the line moved to, when known. */
  cwd: string | null
  /** How it was reached: `sh -c`, `pwsh -EncodedCommand`, `$(…)`, `xargs` and so on. */
  via: string[]
  /** Inline code for an interpreter (`python -c`, `node -e`), read as text only. */
  inlineCode: string | null
  /** A script file the command runs (`bash x.sh`, `pwsh -File x.ps1`, `./x.sh`). */
  scriptFile: string | null
  shell: 'sh' | 'ps' | 'cmd'
}

export type Heredoc = { target: string; tag: string; body: string; read?: boolean }

export type Parsed = {
  commands: SimpleCommand[]
  heredocs: Heredoc[]
  /** Why the line cannot be read for sure, or null. */
  indeterminate: string | null
}

const MAX_DEPTH = 6
const MAX_COMMANDS = 400

type Ctx = { depth: number; out: Parsed; via: string[]; shell: 'sh' | 'ps' | 'cmd' }

/** Base name of a program, lower-cased, without .exe/.cmd/.bat/.ps1 suffix. */
export const progName = (word: string): string =>
  (word.replace(/\\/g, '/').split('/').pop() ?? word).toLowerCase().replace(/\.(exe|cmd|bat|com)$/, '')

/** Join literal string concatenations: ("Remove-" + "VM") becomes "Remove-VM". */
const joinConcats = (s: string): string => {
  let prev = ''
  let cur = s
  for (let i = 0; i < 10 && cur !== prev; i++) {
    prev = cur
    cur = cur
      .replace(/(["'])([^"'`$]*)\1\s*\+\s*(["'])([^"'`$]*)\3/g, (_m, _a, x: string, _b, y: string) => `"${x}${y}"`)
      .replace(/\(\s*(["'])([^"'`$]*)\1\s*\)/g, (_m, _a, x: string) => `"${x}"`)
  }
  return cur
}

/** Decode a PowerShell -EncodedCommand payload (base64 of UTF-16LE). Null when it does not decode. */
export const decodePsEncoded = (b64: string): string | null => {
  try {
    if (!/^[A-Za-z0-9+/=\s]+$/.test(b64)) return null
    const atobFn = (globalThis as { atob?: (s: string) => string }).atob
    if (!atobFn) return null
    const bin = atobFn(b64.replace(/\s+/g, ''))
    if (bin.length % 2 !== 0) return null
    let out = ''
    for (let i = 0; i < bin.length; i += 2) out += String.fromCharCode(bin.charCodeAt(i) | (bin.charCodeAt(i + 1) << 8))
    return out
  } catch {
    return null
  }
}

type Tok = { kind: 'word'; text: string; raw: string; quoted: boolean; dollar: boolean } | { kind: 'op'; text: string } | { kind: 'sub'; text: string; shell: 'sh' | 'ps' }

/** Find the end of a balanced $( … ) or ( … ) starting just after the opening paren. */
const balanced = (s: string, start: number, open: string, close: string): number => {
  let depth = 1
  let q: string | null = null
  for (let i = start; i < s.length; i++) {
    const c = s[i]!
    if (q) {
      if (c === '\\' && q === '"') { i++; continue }
      if (c === q) q = null
      continue
    }
    if (c === '"' || c === "'") { q = c; continue }
    if (c === open) depth++
    else if (c === close) {
      depth--
      if (depth === 0) return i
    }
  }
  return -1
}

/** Tokenize one shell line. Heredoc bodies are pulled out first by the caller. */
const tokenize = (src: string, shell: 'sh' | 'ps' | 'cmd', subs: Tok[], fail: (why: string) => void): Tok[] => {
  const toks: Tok[] = []
  let i = 0
  let word = ''
  let raw = ''
  let quoted = false
  let dollar = false
  let inWord = false
  const esc = shell === 'ps' ? '`' : shell === 'cmd' ? '^' : '\\'
  const flush = () => {
    if (inWord) toks.push({ kind: 'word', text: word, raw, quoted, dollar })
    word = ''
    raw = ''
    quoted = false
    dollar = false
    inWord = false
  }
  while (i < src.length) {
    const c = src[i]!
    // comments
    if (!inWord && c === '#' && shell !== 'cmd') {
      if (shell === 'ps' && src[i - 1] === '<') { i++; continue }
      while (i < src.length && src[i] !== '\n') i++
      continue
    }
    if (shell === 'ps' && c === '<' && src[i + 1] === '#') {
      const end = src.indexOf('#>', i + 2)
      i = end < 0 ? src.length : end + 2
      continue
    }
    if (c === esc && i + 1 < src.length) {
      if (src[i + 1] === '\n') { i += 2; continue }
      word += src[i + 1]
      raw += c + src[i + 1]
      inWord = true
      i += 2
      continue
    }
    if (c === "'") {
      const end = src.indexOf("'", i + 1)
      if (end < 0) { fail('an unclosed single quote'); word += src.slice(i + 1); i = src.length; inWord = true; continue }
      word += src.slice(i + 1, end)
      raw += src.slice(i, end + 1)
      quoted = true
      inWord = true
      i = end + 1
      continue
    }
    if (c === '"') {
      let j = i + 1
      let text = ''
      while (j < src.length && src[j] !== '"') {
        const d = src[j]!
        if ((d === '\\' && shell === 'sh') || (d === '`' && shell === 'ps')) {
          if (j + 1 < src.length) text += src[j + 1]
          j += 2
          continue
        }
        if (d === '$' && src[j + 1] === '(') {
          const end = balanced(src, j + 2, '(', ')')
          if (end < 0) { fail('an unclosed $( inside quotes'); j = src.length; break }
          subs.push({ kind: 'sub', text: src.slice(j + 2, end), shell: shell === 'ps' ? 'ps' : 'sh' })
          text += '\u0000'
          j = end + 1
          continue
        }
        if (d === '`' && shell === 'sh') {
          const end = src.indexOf('`', j + 1)
          if (end < 0) { fail('an unclosed backtick'); j = src.length; break }
          subs.push({ kind: 'sub', text: src.slice(j + 1, end), shell: 'sh' })
          j = end + 1
          continue
        }
        text += d
        j++
      }
      if (j >= src.length && src[src.length - 1] !== '"') fail('an unclosed double quote')
      word += text
      raw += src.slice(i, j + 1)
      quoted = true
      inWord = true
      i = j + 1
      continue
    }
    if (c === '$' && src[i + 1] === '(') {
      const end = balanced(src, i + 2, '(', ')')
      if (end < 0) { fail('an unclosed $('); i = src.length; continue }
      subs.push({ kind: 'sub', text: src.slice(i + 2, end), shell: shell === 'ps' ? 'ps' : 'sh' })
      word += '\u0000'
      raw += src.slice(i, end + 1)
      inWord = true
      i = end + 1
      continue
    }
    if ((c === '<' || c === '>') && src[i + 1] === '(' && shell === 'sh') {
      const end = balanced(src, i + 2, '(', ')')
      if (end < 0) { fail('an unclosed process substitution'); i = src.length; continue }
      subs.push({ kind: 'sub', text: src.slice(i + 2, end), shell: 'sh' })
      word += '\u0000'
      inWord = true
      i = end + 1
      continue
    }
    if (c === '`' && shell === 'sh') {
      const end = src.indexOf('`', i + 1)
      if (end < 0) { fail('an unclosed backtick'); i = src.length; continue }
      subs.push({ kind: 'sub', text: src.slice(i + 1, end), shell: 'sh' })
      word += '\u0000'
      inWord = true
      i = end + 1
      continue
    }
    if (c === '$' && shell !== 'cmd') {
      dollar = dollar || !inWord
    }
    if (c === ' ' || c === '\t' || c === '\r') { flush(); i++; continue }
    if (c === '\n') { flush(); toks.push({ kind: 'op', text: ';' }); i++; continue }
    const two = src.slice(i, i + 2)
    const three = src.slice(i, i + 3)
    if (two === '&&' || two === '||') { flush(); toks.push({ kind: 'op', text: two }); i += 2; continue }
    if (c === ';' || c === '|') { flush(); toks.push({ kind: 'op', text: c }); i++; continue }
    if (c === '&') {
      if (shell === 'ps' && !inWord) { flush(); toks.push({ kind: 'op', text: '&call' }); i++; continue }
      if (two === '&>') { flush(); toks.push({ kind: 'op', text: '>' }); i += 2; continue }
      if (inWord && /\d$|>$/.test(word)) { word += c; raw += c; i++; continue }
      flush(); toks.push({ kind: 'op', text: ';' }); i++; continue
    }
    if (c === '>' || (c === '<' && shell !== 'ps')) {
      const prefix = inWord && /^\d$/.test(word) ? word : ''
      if (prefix) { word = ''; raw = ''; inWord = false }
      flush()
      const op = three === '<<<' ? '<<<' : two === '>>' || two === '<<' ? two : c
      i += op.length
      if (src[i] === '&') {
        // `>&2`, `2>&1`, `<&0`: a descriptor duplication names no file, so nothing after it is a target.
        i++
        while (i < src.length && /[\d-]/.test(src[i]!)) i++
        toks.push({ kind: 'op', text: '>&' })
        continue
      }
      toks.push({ kind: 'op', text: op })
      continue
    }
    if (shell === 'ps' && c === '{' && !inWord) {
      // A script block ({ ... } after &, %, ForEach-Object, Invoke-Command -ScriptBlock) is code.
      const end = balanced(src, i + 1, '{', '}')
      if (end < 0) { fail('an unclosed script block'); i = src.length; continue }
      subs.push({ kind: 'sub', text: src.slice(i + 1, end), shell: 'ps' })
      word += '\u0000'
      inWord = true
      i = end + 1
      continue
    }
    if (c === '(' || c === ')') {
      if (shell === 'ps' && c === '(' && !inWord) {
        const end = balanced(src, i + 1, '(', ')')
        if (end > 0) {
          subs.push({ kind: 'sub', text: src.slice(i + 1, end), shell: 'ps' })
          word += '\u0000'
          inWord = true
          i = end + 1
          continue
        }
      }
      flush(); toks.push({ kind: 'op', text: ';' }); i++; continue
    }
    word += c
    raw += c
    inWord = true
    i++
  }
  flush()
  return toks
}

/** Pull heredoc bodies out (they are data), returning the command text without them. */
const takeHeredocs = (src: string, heredocs: Heredoc[]): string => {
  const lines = src.split('\n')
  const out: string[] = []
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!
    out.push(line)
    // Look for `<<TAG` only where the shell would: not inside quotes, a comment or arithmetic.
    const visible = line
      .replace(/\$\(\([^)]*\)\)|\$\[[^\]]*\]/g, m => ' '.repeat(m.length))
      .replace(/^\s*let\s.*$/, '')
      .replace(/'[^']*'|"(?:[^"\\]|\\.)*"/g, m => (/^["']<<-?\s*\w/.test(m) ? ' '.repeat(m.length) : m.replace(/<</g, '  ')))
      .replace(/(^|\s)#.*$/, '$1')
    const re = /<<(-?)\s*(['"]?)([A-Za-z_][A-Za-z0-9_]*)\2/g
    let m: RegExpExecArray | null
    const tags: Array<{ tag: string; strip: boolean }> = []
    while ((m = re.exec(visible)) !== null) {
      if (visible[m.index + 2] === '<') continue
      tags.push({ tag: m[3]!, strip: m[1] === '-' })
    }
    for (const t of tags) {
      const body: string[] = []
      i++
      while (i < lines.length && (t.strip ? lines[i]!.replace(/^\t+/, '') : lines[i]) !== t.tag) {
        body.push(lines[i]!)
        i++
      }
      const target = (line.match(/^\s*(?:\w+=\S+\s+)*(\S+)/)?.[1] ?? '').toLowerCase()
      const redirect = line.match(/>\s*(\S+)/)?.[1] ?? ''
      heredocs.push({ target: redirect ? `> ${redirect}` : progName(target), tag: t.tag, body: body.join('\n') })
    }
  }
  return out.join('\n')
}

const LAUNCHERS = new Set(['sudo', 'doas', 'env', 'nohup', 'time', 'command', 'builtin', 'exec', 'nice', 'ionice', 'timeout', 'stdbuf', 'xargs', 'wsl', 'start-process', 'saps', 'start', 'call', 'chroot', 'setsid', 'unbuffer', 'caffeinate', 'runas', 'invoke-command', 'icm'])
/** Words the shell reads before a command: `if rm …`, `do rm …`, `{ rm …; }`, `! rm …`. */
const RESERVED = new Set(['!', '{', '}', 'then', 'do', 'else', 'elif', 'if', 'while', 'until', 'coproc'])
const SHELLS = new Set(['sh', 'bash', 'zsh', 'dash', 'ksh', 'fish', 'busybox'])
const PWSH = new Set(['pwsh', 'powershell', 'powershell_ise'])

/** Drop launchers and their own flags; return the remaining argv and how it was reached. */
const stripLaunchers = (argv: string[], env: Record<string, string>, via: string[]): string[] => {
  let a = [...argv]
  for (let guard = 0; guard < 12 && a.length > 0; guard++) {
    const p = progName(a[0]!)
    if (/^[A-Za-z_][A-Za-z0-9_]*=/.test(a[0]!)) {
      const [k, ...v] = a[0]!.split('=')
      env[k!] = v.join('=')
      a = a.slice(1)
      continue
    }
    if (RESERVED.has(a[0]!)) {
      a = a.slice(1)
      continue
    }
    if (!LAUNCHERS.has(p)) break
    // A launcher with nothing after it, or wsl's own management flags, is the command itself.
    if (a.length === 1 || (p === 'wsl' && /^(--(shutdown|unregister|terminate|install|list|set-|export|import|update|status|mount|unmount|version|help)|-[tlsu]$|-l[vq]?$)/.test(a[1] ?? ''))) break
    if (p === 'env' && a.slice(1).every(w => w.startsWith('-') || /^[A-Za-z_][A-Za-z0-9_]*=/.test(w)) && !a.slice(1).some(w => /^[A-Za-z_][A-Za-z0-9_]*=/.test(w))) break
    via.push(p)
    a = a.slice(1)
    if (p === 'env' && a.some(w => w === '-S' || w === '--split-string' || w.startsWith('--split-string='))) {
      // `env -S "cmd args"` runs its string as a command line.
      const i = a.findIndex(w => w === '-S' || w.startsWith('--split-string'))
      const str = a[i]!.includes('=') ? a[i]!.split('=').slice(1).join('=') : a[i + 1] ?? ''
      a = [...str.split(/\s+/).filter(Boolean), ...a.slice(a[i]!.includes('=') ? i + 1 : i + 2)]
      continue
    }
    if (p === 'command' || p === 'builtin') {
      while (a.length && /^-[pvV]+$/.test(a[0]!)) a = a.slice(1)
    } else if (p === 'exec') {
      while (a.length && a[0]!.startsWith('-')) a = a.slice(a[0] === '-a' ? 2 : 1)
    } else if (p === 'time') {
      while (a.length && /^-[pv]$|^--(portability|verbose)$/.test(a[0]!)) a = a.slice(1)
      while (a.length && /^-[of]$|^--(output|format)$/.test(a[0]!)) a = a.slice(2)
    } else if (p === 'setsid' || p === 'nohup' || p === 'unbuffer' || p === 'caffeinate') {
      while (a.length && a[0]!.startsWith('-')) a = a.slice(1)
    } else if (p === 'chroot') {
      while (a.length && a[0]!.startsWith('-')) a = a.slice(/^--(userspec|groups)$/.test(a[0]!) ? 2 : 1)
      a = a.slice(1)
    } else if (p === 'env') {
      while (a.length && (a[0]!.startsWith('-') || /^[A-Za-z_][A-Za-z0-9_]*=/.test(a[0]!))) {
        if (a[0] === '-u' || a[0] === '-C' || a[0] === '-S') a = a.slice(2)
        else if (a[0]!.includes('=') && !a[0]!.startsWith('-')) {
          const [k, ...v] = a[0]!.split('=')
          env[k!] = v.join('=')
          a = a.slice(1)
        } else a = a.slice(1)
      }
    } else if (p === 'timeout') {
      while (a.length && a[0]!.startsWith('-')) a = a.slice(a[0] === '-s' || a[0] === '-k' ? 2 : 1)
      a = a.slice(1)
    } else if (p === 'nice' || p === 'ionice') {
      while (a.length && a[0]!.startsWith('-')) a = a.slice(a[0] === '-n' || a[0] === '-c' ? 2 : 1)
    } else if (p === 'xargs') {
      while (a.length && a[0]!.startsWith('-')) a = a.slice(/^-(n|I|L|P|d|E|s|a)$|^--(max-args|replace|max-lines|max-procs|delimiter|eof|max-chars|arg-file)$/.test(a[0]!) ? 2 : 1)
    } else if (p === 'sudo' || p === 'doas' || p === 'runas') {
      while (a.length && a[0]!.startsWith('-')) a = a.slice(/^-(u|g|p|C|h|U)$/.test(a[0]!) ? 2 : 1)
    } else if (p === 'wsl') {
      while (a.length && a[0]!.startsWith('-')) {
        if (a[0] === '-e' || a[0] === '--exec' || a[0] === '--') { a = a.slice(1); break }
        a = a.slice(/^(-d|--distribution|-u|--user|--cd)$/.test(a[0]!) ? 2 : 1)
      }
    } else if (p === 'start-process' || p === 'start' || p === 'saps') {
      const fp = a.findIndex(w => /^-(filepath)$/i.test(w))
      const prog = fp >= 0 ? a[fp + 1] : a.find(w => !w.startsWith('-') && !/^\/(b|wait|min|max)$/i.test(w))
      const ai = a.findIndex(w => /^-(argumentlist|args)$/i.test(w))
      const args = ai >= 0 ? (a[ai + 1] ?? '').split(/[\s,]+/).filter(Boolean) : []
      a = prog ? [prog, ...args] : []
    } else if (p === 'stdbuf') {
      while (a.length && a[0]!.startsWith('-')) a = a.slice(/^-[ioe]$/.test(a[0]!) ? 2 : 1)
    }
  }
  return a
}

const pushCommand = (ctx: Ctx, cmd: SimpleCommand): void => {
  if (ctx.out.commands.length >= MAX_COMMANDS) {
    ctx.out.indeterminate = ctx.out.indeterminate ?? `more than ${MAX_COMMANDS} commands on one line`
    return
  }
  ctx.out.commands.push(cmd)
}

const parseInto = (src: string, ctx: Ctx): void => {
  if (ctx.depth > MAX_DEPTH) {
    ctx.out.indeterminate = ctx.out.indeterminate ?? `nesting deeper than ${MAX_DEPTH} levels`
    return
  }
  let text = src.replace(/\$\{IFS\}|\$IFS\b/g, ' ')
  if (ctx.shell === 'cmd') text = text.replace(/\^(.)/g, '$1')
  if (ctx.shell === 'ps') text = joinConcats(text)
  text = takeHeredocs(text, ctx.out.heredocs)
  const subs: Tok[] = []
  const toks = tokenize(text, ctx.shell, subs, why => { ctx.out.indeterminate = ctx.out.indeterminate ?? why })
  for (const s of subs) if (s.kind === 'sub') parseInto(s.text, { ...ctx, depth: ctx.depth + 1, via: [...ctx.via, s.shell === 'ps' ? '$( ) in PowerShell' : '$( )'], shell: s.shell })

  let cwd: string | null = null
  let cur: Array<Extract<Tok, { kind: 'word' }>> = []
  let redirects: Redirect[] = []
  let call = false
  let pendingRedirect: string | null = null
  let piped = false
  let nextPiped = false
  const finish = () => {
    piped = nextPiped
    if (cur.length === 0 && redirects.length === 0) return
    const words = cur
    cur = []
    const reds = redirects
    redirects = []
    const env: Record<string, string> = {}
    const via = [...ctx.via]
    const argvRaw = words.map(w => w.text)
    const firstReal = words.find(w => !RESERVED.has(w.text) && !/^[A-Za-z_]\w*=/.test(w.raw))
    if (firstReal && firstReal.raw.includes('$') && words[words.indexOf(firstReal) + 1]?.text !== '=' && !/^\$[\w:]+=/.test(firstReal.raw)) {
      ctx.out.indeterminate = ctx.out.indeterminate ?? `a command built at run time (${firstReal.raw.slice(0, 40)})`
    }
    call = false
    // PowerShell's dot-source operator runs its argument like `&` does.
    const argv = stripLaunchers(ctx.shell === 'ps' && argvRaw[0] === '.' ? argvRaw.slice(1) : argvRaw, env, via)
    if (argv.length === 0) {
      if (Object.keys(env).length > 0 || reds.length > 0) pushCommand(ctx, { argv: [], prog: '', env, redirects: reds, cwd, via, inlineCode: null, scriptFile: null, shell: ctx.shell })
      return
    }
    const prog = progName(argv[0]!)
    // cd moves the folder for the commands after it on this line.
    if ((prog === 'cd' || prog === 'set-location' || prog === 'pushd' || prog === 'sl') && argv[1]) {
      cwd = argv[argv[1] === '-Path' || argv[1] === '-LiteralPath' ? 2 : 1] ?? cwd
    }
    const base: SimpleCommand = { argv, prog, env, redirects: reds, cwd, via, inlineCode: null, scriptFile: null, shell: ctx.shell }
    /** A shell reading its script from stdin: a here-string or heredoc is parsed as code; a pipe cannot be read. */
    const stdinScript = (who: string, sh: 'sh' | 'ps') => {
      const hs = reds.find(r => r.op === '<<<')
      const hd = ctx.out.heredocs.find(h => !h.read && h.target === who)
      if (hs) parseInto(hs.target, { ...ctx, depth: ctx.depth + 1, via: [...via, `${who} <<<`], shell: sh })
      else if (hd) {
        hd.read = true
        parseInto(hd.body, { ...ctx, depth: ctx.depth + 1, via: [...via, `${who} <<heredoc`], shell: sh })
      } else if (piped || reds.some(r => r.op === '<')) ctx.out.indeterminate = ctx.out.indeterminate ?? `${who} reads its script from stdin`
    }
    const inner = (script: string, how: string, shell: 'sh' | 'ps' | 'cmd') => parseInto(script, { ...ctx, depth: ctx.depth + 1, via: [...via, how], shell })

    if (SHELLS.has(prog)) {
      const ci = argv.findIndex((w, k) => k > 0 && /^-[a-z]*c[a-z]*$/.test(w))
      const script = ci > 0 ? argv.slice(ci + 1).find(w => w !== '--') : undefined
      if (ci > 0 && script !== undefined) { pushCommand(ctx, base); inner(script, `${prog} -c`, 'sh'); return }
      const file = argv.slice(1).find(w => !w.startsWith('-'))
      pushCommand(ctx, { ...base, scriptFile: file ?? null })
      if (!file || argv.includes('-s')) stdinScript(prog, 'sh')
      return
    }
    if (PWSH.has(prog)) {
      // PowerShell takes any unambiguous prefix of a parameter, with - or /.
      const param = (w: string, full: string, min: number) => /^[-/]/.test(w) && w.length - 1 >= min && full.startsWith(w.slice(1).toLowerCase())
      const ei = argv.findIndex((w, k) => k > 0 && (param(w, 'encodedcommand', 1) || /^[-/]ec$/i.test(w)) && !param(w, 'executionpolicy', 2))
      if (ei > 0) {
        const decoded = decodePsEncoded(argv[ei + 1] ?? '')
        pushCommand(ctx, base)
        if (decoded === null) ctx.out.indeterminate = ctx.out.indeterminate ?? 'a PowerShell -EncodedCommand that does not decode'
        else inner(decoded, 'pwsh -EncodedCommand', 'ps')
        return
      }
      const fi = argv.findIndex((w, k) => k > 0 && param(w, 'file', 1))
      if (fi > 0) { pushCommand(ctx, { ...base, scriptFile: argv[fi + 1] ?? null }); return }
      const ci = argv.findIndex((w, k) => k > 0 && param(w, 'command', 1) && !param(w, 'configurationname', 3))
      const valued = /^[-/](executionpolicy|ex|ep|windowstyle|w|outputformat|o|of|inputformat|if|version|v|psconsolefile|configurationname|workingdirectory|wd)$/i
      const rest = ci > 0 ? argv.slice(ci + 1) : argv.slice(1).filter((w, k, all) => !/^[-/]/.test(w) && !valued.test(all[k - 1] ?? ''))
      pushCommand(ctx, base)
      if (rest.length > 0) {
        if (rest[0] === '-') ctx.out.indeterminate = ctx.out.indeterminate ?? 'a PowerShell script read from stdin'
        else inner(rest.join(' '), 'pwsh -Command', 'ps')
      } else stdinScript(prog, 'ps')
      return
    }
    if (prog === 'cmd') {
      const ci = argv.findIndex((w, k) => k > 0 && /^\/[ck]$/i.test(w))
      pushCommand(ctx, base)
      if (ci > 0) inner(argv.slice(ci + 1).join(' '), 'cmd /c', 'cmd')
      return
    }
    if (prog === 'eval' || prog === 'iex' || prog === 'invoke-expression') {
      pushCommand(ctx, base)
      const arg = words.slice(1).find(w => !w.text.startsWith('-'))
      if (!arg) {
        ctx.out.indeterminate = ctx.out.indeterminate ?? `${prog} reading from a pipe`
        return
      }
      if (arg.dollar && !arg.quoted) ctx.out.indeterminate = ctx.out.indeterminate ?? `${prog} of a variable`
      inner(argv.slice(1).filter(w => !/^-command$/i.test(w)).join(' '), prog, prog === 'eval' ? 'sh' : 'ps')
      return
    }
    if (prog === 'git' && argv.includes('submodule') && argv.includes('foreach')) {
      pushCommand(ctx, base)
      const fi = argv.indexOf('foreach')
      const script = argv.slice(fi + 1).filter(w => !w.startsWith('--')).join(' ')
      if (script) inner(script, 'git submodule foreach', 'sh')
      return
    }
    if (prog === 'find') {
      const ei = argv.findIndex(w => w === '-exec' || w === '-execdir' || w === '-ok')
      pushCommand(ctx, base)
      if (ei > 0) {
        const end = argv.findIndex((w, k) => k > ei && (w === ';' || w === '+' || w === '\\;'))
        const sub = argv.slice(ei + 1, end > 0 ? end : undefined).map(w => (w === '{}' ? 'FILE' : w))
        if (sub.length > 0) {
          const env2: Record<string, string> = {}
          const via2 = [...via, 'find -exec']
          const a2 = stripLaunchers(sub, env2, via2)
          if (a2.length) pushCommand(ctx, { argv: a2, prog: progName(a2[0]!), env: env2, redirects: [], cwd, via: via2, inlineCode: null, scriptFile: null, shell: ctx.shell })
        }
      }
      return
    }
    if (/^(python[0-9.]*|py|node|deno|bun|ruby|perl|php)$/.test(prog)) {
      const ci = argv.findIndex((w, k) => k > 0 && /^-(c|e|-eval|r)$/.test(w))
      if (ci > 0) { pushCommand(ctx, { ...base, inlineCode: argv[ci + 1] ?? '' }); return }
      const file = argv.slice(1).find(w => !w.startsWith('-'))
      pushCommand(ctx, { ...base, scriptFile: file && /\.(py|js|mjs|ts|rb|pl|php)$/.test(file) ? file : null })
      return
    }
    if (/^\.?\.?\//.test(argv[0]!) && /\.(sh|bash|ps1)$/.test(argv[0]!)) {
      pushCommand(ctx, { ...base, scriptFile: argv[0]! })
      return
    }
    if ((prog === 'source' || prog === '.') && argv[1]) {
      if (/^\/dev\/(stdin|fd\/0)$|^-$/.test(argv[1])) stdinScript(prog, 'sh')
      pushCommand(ctx, { ...base, scriptFile: argv[1] })
      return
    }
    if (/\[scriptblock\]::create|\.InvokeScript\(|\.AddScript\(|\$ExecutionContext/i.test(words.map(w => w.raw).join(' '))) {
      ctx.out.indeterminate = ctx.out.indeterminate ?? 'a script block built at run time'
    }
    pushCommand(ctx, base)
  }
  for (const t of toks) {
    if (t.kind === 'op') {
      if (t.text === '&call') { finish(); nextPiped = false; call = true; continue }
      if (t.text === '>&') { pendingRedirect = null; continue }
      if (t.text === '>' || t.text === '>>' || t.text === '<' || t.text === '<<<' || t.text === '<<') { pendingRedirect = t.text; continue }
      pendingRedirect = null
      finish()
      nextPiped = t.text === '|'
      continue
    }
    if (t.kind !== 'word') continue
    if (pendingRedirect) {
      if (pendingRedirect !== '<<') redirects.push({ op: pendingRedirect, target: t.text })
      pendingRedirect = null
      continue
    }
    cur.push(t)
  }
  finish()
}

/** Read a command line. `shell` is the tool that runs it: Bash ('sh') or PowerShell ('ps'). */
export const parseShell = (command: string, shell: 'sh' | 'ps' = 'sh'): Parsed => {
  const out: Parsed = { commands: [], heredocs: [], indeterminate: null }
  parseInto(command, { depth: 0, out, via: [], shell })
  return out
}

/** git's subcommand after global options, with the -C folder and -c settings it was given. */
export const gitSub = (argv: readonly string[]): { sub: string; args: string[]; dir: string | null; configs: string[]; gitDir: boolean } => {
  let i = 1
  let dir: string | null = null
  const configs: string[] = []
  let gitDir = false
  while (i < argv.length && argv[i]!.startsWith('-')) {
    const w = argv[i]!
    if (w === '-C') { dir = argv[i + 1] ?? null; i += 2; continue }
    if (w === '-c') { configs.push(argv[i + 1] ?? ''); i += 2; continue }
    if (w.startsWith('--git-dir') || w.startsWith('--work-tree')) { gitDir = true; i += w.includes('=') ? 1 : 2; continue }
    if (w === '--namespace' || w === '--exec-path') { i += 2; continue }
    i++
  }
  return { sub: (argv[i] ?? '').toLowerCase(), args: argv.slice(i + 1), dir, configs, gitDir }
}

/** Every path a command writes to: redirect targets and the write-verb targets of common tools. */
export const writeTargets = (c: SimpleCommand): string[] => {
  const out = c.redirects.filter(r => r.op === '>' || r.op === '>>').map(r => r.target)
  const a = c.argv
  const nonFlags = (from: number) => a.slice(from).filter(w => !w.startsWith('-'))
  switch (c.prog) {
    case 'tee': out.push(...nonFlags(1)); break
    case 'cp': case 'mv': case 'install': case 'ln': case 'rsync': case 'copy': case 'move': case 'xcopy': case 'robocopy': {
      const nf = nonFlags(1)
      if (nf.length > 0) out.push(nf[nf.length - 1]!)
      if (c.prog === 'mv' || c.prog === 'move') out.push(...nf.slice(0, -1))
      break
    }
    case 'rm': case 'rmdir': case 'del': case 'erase': case 'rd': case 'unlink': case 'shred': case 'truncate': case 'touch': case 'chmod': case 'chown':
      out.push(...nonFlags(c.prog === 'chmod' || c.prog === 'chown' ? 2 : 1)); break
    case 'sed': if (a.some(w => /^-i/.test(w) || w === '--in-place')) out.push(...nonFlags(1).slice(1)); break
    case 'perl': if (a.some(w => /^-[a-z]*i/.test(w))) out.push(...nonFlags(1).slice(1)); break
    case 'dd': { const of = a.find(w => w.startsWith('of=')); if (of) out.push(of.slice(3)); break }
    case 'set-content': case 'add-content': case 'out-file': case 'remove-item': case 'clear-content': case 'new-item': case 'copy-item': case 'move-item': case 'rename-item': case 'ri': case 'rm.exe': case 'sc': case 'ac': {
      const pi = a.findIndex(w => /^-(path|literalpath|destination|filepath)$/i.test(w))
      if (pi > 0 && a[pi + 1]) out.push(a[pi + 1]!)
      else { const nf = nonFlags(1); if (nf[0]) out.push(c.prog === 'copy-item' || c.prog === 'move-item' ? nf[nf.length - 1]! : nf[0]) }
      break
    }
    default: break
  }
  return out.filter(Boolean)
}
